//! This module contains the [HintType] enum.

use crate::errors::{HintParsingError, OracleProviderError};
use alloc::vec::Vec;
use kona_preimage::HintWriterClient;
use num_enum::{IntoPrimitive, TryFromPrimitive};

/// A [Hint] is parsed in the format `<hint_type> <hint_data>`, where `<hint_type>` is a string that
/// represents the type of hint, and `<hint_data>` is the data associated with the hint (bytes
/// encoded as hex UTF-8).
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct Hint<HT> {
    /// The type of hint.
    pub ty: HT,
    /// The data associated with the hint.
    pub data: Vec<u8>,
}

impl<HT> Hint<HT>
where
    HT: Into<u8>,
{
    /// Creates a new [Hint] with the specified type and data.
    pub fn new(ty: HT, data: Vec<u8>) -> Self {
        Self { ty, data }
    }

    /// Appends more data to [Hint::data].
    pub fn with_data<T: AsRef<[u8]>>(mut self, data: T) -> Self {
        self.data.extend_from_slice(data.as_ref());
        self
    }

    /// Sends the hint to the passed [HintWriterClient].
    pub async fn send<T: HintWriterClient>(mut self, comms: &T) -> Result<(), OracleProviderError> {
        let mut buffer = core::mem::take(&mut self.data);
        buffer.insert(0, self.ty.into());
        comms.write(&buffer).await.map_err(OracleProviderError::Preimage)
    }
}

impl<HT> TryFrom<&[u8]> for Hint<HT>
where
    HT: TryFrom<u8>,
{
    type Error = HintParsingError;

    fn try_from(value: &[u8]) -> Result<Self, Self::Error> {
        if value.is_empty() {
            return Err(HintParsingError::EmptyHintData);
        }

        let ty = HT::try_from(value[0]).map_err(|_| HintParsingError::UnknownHintType(value[0]))?;
        let data = value[1..].to_vec();

        Ok(Self { ty, data })
    }
}

/// The [HintType] enum is used to specify the type of hint that was received.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)] //
#[derive(IntoPrimitive, TryFromPrimitive)]
#[repr(u8)]
pub enum HintType {
    /// A hint that specifies the block header of a layer 1 block.
    L1BlockHeader = 0x01,
    /// A hint that specifies the transactions of a layer 1 block.
    L1Transactions = 0x02,
    /// A hint that specifies the state node of a layer 1 block.
    L1Receipts = 0x03,
    /// A hint that specifies a blob in the layer 1 beacon chain.
    L1Blob = 0x04,
    /// A hint that specifies a precompile call on layer 1.
    L1Precompile = 0x05,
    /// A hint that specifies the block header of a layer 2 block.
    L2BlockHeader = 0x06,
    /// A hint that specifies the transactions of a layer 2 block.
    L2Transactions = 0x07,
    /// A hint that specifies the code of a contract on layer 2.
    L2Code = 0x20,
    /// A hint that specifies the preimage of the starting L2 output root on layer 2.
    StartingL2Output = 0x30,
    /// A hint that specifies the state node in the L2 state trie.
    L2StateNode = 0x50,
    /// A hint that specifies the proof on the path to an account in the L2 state trie.
    L2AccountProof = 0x51,
    /// A hint that specifies the proof on the path to a storage slot in an account within in the
    /// L2 state trie.
    L2AccountStorageProof = 0x52,
    /// A hint that specifies bulk storage of all the code, state and keys generated by an
    /// execution witness.
    L2PayloadWitness = 0x70,
}

impl HintType {
    /// Creates a new [Hint] from `self` and the specified data. The data passed will be
    /// concatenated into a single byte array before being stored in the resulting [Hint].
    pub fn with_data(self, data: &[&[u8]]) -> Hint<Self> {
        let total_len = data.iter().map(|d| d.len()).sum();
        let hint_data = data.iter().fold(Vec::with_capacity(total_len), |mut acc, d| {
            acc.extend_from_slice(d);
            acc
        });
        Hint::new(self, hint_data)
    }
}
