//! This module contains the [HintType] enum.

use crate::errors::{HintParsingError, OracleProviderError};
use alloc::vec::Vec;
use alloy_primitives::Bytes;
use kona_preimage::HintWriterClient;

/// A [Hint] is parsed in the format `<hint_type> <hint_data>`, where `<hint_type>` is a string that
/// represents the type of hint, and `<hint_data>` is the data associated with the hint (bytes
/// encoded as hex UTF-8).
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct Hint<HT> {
    /// The type of hint.
    pub ty: HT,
    /// The data associated with the hint.
    pub data: Bytes,
}

impl<HT> Hint<HT>
where
    HT: Copy + Into<u8>,
{
    /// Creates a new [Hint] with the specified type and data.
    pub fn new<T: Into<Bytes>>(ty: HT, data: T) -> Self {
        Self { ty, data: data.into() }
    }

    /// Splits the [Hint] into its components.
    pub fn split(self) -> (HT, Bytes) {
        (self.ty, self.data)
    }

    /// Appends more data to [Hint::data].
    pub fn with_data<T: AsRef<[u8]>>(self, data: T) -> Self {
        // No-op if the data is empty.
        if data.as_ref().is_empty() {
            return self;
        }

        let mut hint_data = Vec::with_capacity(self.data.len() + data.as_ref().len());
        hint_data.extend_from_slice(self.data.as_ref());
        hint_data.extend_from_slice(data.as_ref());

        Self { data: hint_data.into(), ..self }
    }

    /// Sends the hint to the passed [HintWriterClient].
    pub async fn send<T: HintWriterClient>(&self, comms: &T) -> Result<(), OracleProviderError> {
        comms.write(&self.encode()).await.map_err(OracleProviderError::Preimage)
    }

    /// Encodes the hint as a string.
    pub fn encode(&self) -> Bytes {
        let mut buffer = Vec::with_capacity(self.data.len() + 1);
        buffer.push(self.ty.into());
        buffer.extend_from_slice(self.data.as_ref());
        Bytes::from(buffer)
    }
}

impl<HT: TryFrom<u8>> TryFrom<&Bytes> for Hint<HT> {
    type Error = HintParsingError;

    fn try_from(value: &Bytes) -> Result<Self, Self::Error> {
        if value.is_empty() {
            return Err(HintParsingError::EmptyHintData);
        }
        let ty = HT::try_from(value[0]).map_err(|_| HintParsingError::UnknownHintType(value[0]))?;
        let data = value.slice(1..);
        Ok(Self { ty, data })
    }
}

/// The [HintType] enum is used to specify the type of hint that was received.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
#[repr(u8)] // Start with 0x80 to ensure it is non-ASCII, making it easy to tell apart from the old format that uses ASCII characters.
pub enum HintType {
    /// A hint that specifies the block header of a layer 1 block.
    L1BlockHeader = 0x80,
    /// A hint that specifies the transactions of a layer 1 block.
    L1Transactions = 0x81,
    /// A hint that specifies the state node of a layer 1 block.
    L1Receipts = 0x82,
    /// A hint that specifies a blob in the layer 1 beacon chain.
    L1Blob = 0x83,
    /// A hint that specifies a precompile call on layer 1.
    L1Precompile = 0x84,
    /// A hint that specifies the block header of a layer 2 block.
    L2BlockHeader = 0x85,
    /// A hint that specifies the transactions of a layer 2 block.
    L2Transactions = 0x86,
    /// A hint that specifies the code of a contract on layer 2.
    L2Code = 0x8c,
    /// A hint that specifies the preimage of the starting L2 output root on layer 2.
    StartingL2Output = 0x90,
    /// A hint that specifies the state node in the L2 state trie.
    L2StateNode = 0x9c,
    /// A hint that specifies the proof on the path to an account in the L2 state trie.
    L2AccountProof = 0x9d,
    /// A hint that specifies the proof on the path to a storage slot in an account within in the
    /// L2 state trie.
    L2AccountStorageProof = 0x9e,
    /// A hint that specifies bulk storage of all the code, state and keys generated by an
    /// execution witness.
    L2PayloadWitness = 0xa4,
}

impl From<HintType> for u8 {
    fn from(v: HintType) -> Self {
        v as _
    }
}

impl TryFrom<u8> for HintType {
    type Error = u8;

    fn try_from(value: u8) -> Result<Self, Self::Error> {
        Ok(match value {
            0x80 => HintType::L1BlockHeader,
            0x81 => HintType::L1Transactions,
            0x82 => HintType::L1Receipts,
            0x83 => HintType::L1Blob,
            0x84 => HintType::L1Precompile,
            0x85 => HintType::L2BlockHeader,
            0x86 => HintType::L2Transactions,
            0x8c => HintType::L2Code,
            0x90 => HintType::StartingL2Output,
            0x9c => HintType::L2StateNode,
            0x9d => HintType::L2AccountProof,
            0x9e => HintType::L2AccountStorageProof,
            0xa4 => HintType::L2PayloadWitness,
            other => return Err(other),
        })
    }
}

impl HintType {
    /// Creates a new [Hint] from `self` and the specified data. The data passed will be
    /// concatenated into a single byte array before being stored in the resulting [Hint].
    pub fn with_data(self, data: &[&[u8]]) -> Hint<Self> {
        let total_len = data.iter().map(|d| d.len()).sum();
        let hint_data = data.iter().fold(Vec::with_capacity(total_len), |mut acc, d| {
            acc.extend_from_slice(d);
            acc
        });
        Hint::new(self, hint_data)
    }
}
