//! This module contains the [HintType] enum.

use alloc::vec::Vec;
use kona_proof::Hint;

/// The [HintType] enum is used to specify the type of hint that was received.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
#[repr(u8)]
pub enum HintType {
    /// A hint that specifies the block header of a layer 1 block.
    L1BlockHeader = 0x80,
    /// A hint that specifies the transactions of a layer 1 block.
    L1Transactions = 0x81,
    /// A hint that specifies the state node of a layer 1 block.
    L1Receipts = 0x82,
    /// A hint that specifies a blob in the layer 1 beacon chain.
    L1Blob = 0x83,
    /// A hint that specifies a precompile call on layer 1.
    L1Precompile = 0x84,
    /// A hint that specifies the block header of a layer 2 block.
    L2BlockHeader = 0x85,
    /// A hint that specifies the transactions of a layer 2 block.
    L2Transactions = 0x86,
    /// A hint that specifies the receipts of a layer 2 block.
    L2Receipts = 0x88,
    /// A hint that specifies the code of a contract on layer 2.
    L2Code = 0x8c,
    /// A hint that specifies the preimage of the agreed upon pre-state claim.
    AgreedPreState = 0x94,
    /// A hint that specifies the preimage of an L2 output root within the agreed upon pre-state,
    /// by chain ID.
    L2OutputRoot = 0x98,
    /// A hint that specifies the state node in the L2 state trie.
    L2StateNode = 0x9c,
    /// A hint that specifies the proof on the path to an account in the L2 state trie.
    L2AccountProof = 0x9d,
    /// A hint that specifies the proof on the path to a storage slot in an account within in the
    /// L2 state trie.
    L2AccountStorageProof = 0x9e,
    /// A hint that specifies loading the payload witness for an optimistic block.
    L2BlockData = 0xa0,
    /// A hint that specifies bulk storage of all the code, state and keys generated by an
    /// execution witness.
    L2PayloadWitness = 0xa4,
}

impl From<HintType> for u8 {
    fn from(v: HintType) -> Self {
        v as _
    }
}

impl TryFrom<u8> for HintType {
    type Error = u8;

    fn try_from(value: u8) -> Result<Self, Self::Error> {
        Ok(match value {
            0x80 => HintType::L1BlockHeader,
            0x81 => HintType::L1Transactions,
            0x82 => HintType::L1Receipts,
            0x83 => HintType::L1Blob,
            0x84 => HintType::L1Precompile,
            0x85 => HintType::L2BlockHeader,
            0x86 => HintType::L2Transactions,
            0x88 => HintType::L2Receipts,
            0x8c => HintType::L2Code,
            0x94 => HintType::AgreedPreState,
            0x98 => HintType::L2OutputRoot,
            0x9c => HintType::L2StateNode,
            0x9d => HintType::L2AccountProof,
            0x9e => HintType::L2AccountStorageProof,
            0xa0 => HintType::L2BlockData,
            0xa4 => HintType::L2PayloadWitness,
            other => return Err(other),
        })
    }
}

impl HintType {
    /// Creates a new [Hint] from `self` and the specified data. The data passed will be
    /// concatenated into a single byte array before being stored in the resulting [Hint].
    pub fn with_data(self, data: &[&[u8]]) -> Hint<Self> {
        let total_len = data.iter().map(|d| d.len()).sum();
        let hint_data = data.iter().fold(Vec::with_capacity(total_len), |mut acc, d| {
            acc.extend_from_slice(d);
            acc
        });
        Hint::new(self, hint_data)
    }
}
