//! This module contains the [HintType] enum.

use alloc::vec::Vec;
use kona_proof::Hint;
use num_enum::{IntoPrimitive, TryFromPrimitive};

/// The [HintType] enum is used to specify the type of hint that was received.
#[derive(
    Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, IntoPrimitive, TryFromPrimitive,
)]
#[repr(u8)]
pub enum HintType {
    /// A hint that specifies the block header of a layer 1 block.
    L1BlockHeader = 0x01,
    /// A hint that specifies the transactions of a layer 1 block.
    L1Transactions = 0x02,
    /// A hint that specifies the state node of a layer 1 block.
    L1Receipts = 0x03,
    /// A hint that specifies a blob in the layer 1 beacon chain.
    L1Blob = 0x04,
    /// A hint that specifies a precompile call on layer 1.
    L1Precompile = 0x05,
    /// A hint that specifies the block header of a layer 2 block.
    L2BlockHeader = 0x06,
    /// A hint that specifies the transactions of a layer 2 block.
    L2Transactions = 0x07,
    /// A hint that specifies the receipts of a layer 2 block.
    L2Receipts = 0x10,
    /// A hint that specifies the code of a contract on layer 2.
    L2Code = 0x20,
    /// A hint that specifies the preimage of the agreed upon pre-state claim.
    AgreedPreState = 0x40,
    /// A hint that specifies the preimage of an L2 output root within the agreed upon pre-state,
    /// by chain ID.
    L2OutputRoot = 0x41,
    /// A hint that specifies the state node in the L2 state trie.
    L2StateNode = 0x50,
    /// A hint that specifies the proof on the path to an account in the L2 state trie.
    L2AccountProof = 0x51,
    /// A hint that specifies the proof on the path to a storage slot in an account within in the
    /// L2 state trie.
    L2AccountStorageProof = 0x52,
    /// A hint that specifies loading the payload witness for an optimistic block.
    L2BlockData = 0x60,
    /// A hint that specifies bulk storage of all the code, state and keys generated by an
    /// execution witness.
    L2PayloadWitness = 0x70,
}

impl HintType {
    /// Creates a new [Hint] from `self` and the specified data. The data passed will be
    /// concatenated into a single byte array before being stored in the resulting [Hint].
    pub fn with_data(self, data: &[&[u8]]) -> Hint<Self> {
        let total_len = data.iter().map(|d| d.len()).sum();
        let hint_data = data.iter().fold(Vec::with_capacity(total_len), |mut acc, d| {
            acc.extend_from_slice(d);
            acc
        });
        Hint::new(self, hint_data)
    }
}
